/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteRouteImport } from './routes/design-system/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as DesignSystemIndexRouteImport } from './routes/design-system/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as DesignSystemTypographyRouteImport } from './routes/design-system/typography'
import { Route as DesignSystemColorsRouteImport } from './routes/design-system/colors'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppWorkflowsRouteImport } from './routes/_app/workflows'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppPortalsRouteImport } from './routes/_app/portals'
import { Route as AppFormsRouteImport } from './routes/_app/forms'
import { Route as AppFoldersRouteImport } from './routes/_app/folders'
import { Route as DesignSystemComponentsIndexRouteImport } from './routes/design-system/components/index'
import { Route as DesignSystemComponentsTreeRouteImport } from './routes/design-system/components/tree'
import { Route as DesignSystemComponentsTourRouteImport } from './routes/design-system/components/tour'
import { Route as DesignSystemComponentsTooltipRouteImport } from './routes/design-system/components/tooltip'
import { Route as DesignSystemComponentsToastRouteImport } from './routes/design-system/components/toast'
import { Route as DesignSystemComponentsTimelineRouteImport } from './routes/design-system/components/timeline'
import { Route as DesignSystemComponentsTabsRouteImport } from './routes/design-system/components/tabs'
import { Route as DesignSystemComponentsTableRouteImport } from './routes/design-system/components/table'
import { Route as DesignSystemComponentsStepperRouteImport } from './routes/design-system/components/stepper'
import { Route as DesignSystemComponentsSliderRouteImport } from './routes/design-system/components/slider'
import { Route as DesignSystemComponentsSignaturePadRouteImport } from './routes/design-system/components/signature-pad'
import { Route as DesignSystemComponentsSegmentGroupRouteImport } from './routes/design-system/components/segment-group'
import { Route as DesignSystemComponentsScrollAreaRouteImport } from './routes/design-system/components/scroll-area'
import { Route as DesignSystemComponentsRatingRouteImport } from './routes/design-system/components/rating'
import { Route as DesignSystemComponentsRangeSliderRouteImport } from './routes/design-system/components/range-slider'
import { Route as DesignSystemComponentsQrCodeRouteImport } from './routes/design-system/components/qr-code'
import { Route as DesignSystemComponentsProgressSemiCircleRouteImport } from './routes/design-system/components/progress-semi-circle'
import { Route as DesignSystemComponentsProgressCircleRouteImport } from './routes/design-system/components/progress-circle'
import { Route as DesignSystemComponentsProgressRouteImport } from './routes/design-system/components/progress'
import { Route as DesignSystemComponentsPopoverRouteImport } from './routes/design-system/components/popover'
import { Route as DesignSystemComponentsPaginationRouteImport } from './routes/design-system/components/pagination'
import { Route as DesignSystemComponentsModalRouteImport } from './routes/design-system/components/modal'
import { Route as DesignSystemComponentsMenuRouteImport } from './routes/design-system/components/menu'
import { Route as DesignSystemComponentsInputTimeRouteImport } from './routes/design-system/components/input-time'
import { Route as DesignSystemComponentsInputTextareaRouteImport } from './routes/design-system/components/input-textarea'
import { Route as DesignSystemComponentsInputTextRouteImport } from './routes/design-system/components/input-text'
import { Route as DesignSystemComponentsInputSwitchGroupRouteImport } from './routes/design-system/components/input-switch-group'
import { Route as DesignSystemComponentsInputSwitchRouteImport } from './routes/design-system/components/input-switch'
import { Route as DesignSystemComponentsInputSelectMultipleRouteImport } from './routes/design-system/components/input-select-multiple'
import { Route as DesignSystemComponentsInputSelectRouteImport } from './routes/design-system/components/input-select'
import { Route as DesignSystemComponentsInputRadioGroupRouteImport } from './routes/design-system/components/input-radio-group'
import { Route as DesignSystemComponentsInputRadioCardRouteImport } from './routes/design-system/components/input-radio-card'
import { Route as DesignSystemComponentsInputRadioRouteImport } from './routes/design-system/components/input-radio'
import { Route as DesignSystemComponentsInputPinRouteImport } from './routes/design-system/components/input-pin'
import { Route as DesignSystemComponentsInputPasswordRouteImport } from './routes/design-system/components/input-password'
import { Route as DesignSystemComponentsInputNumberRouteImport } from './routes/design-system/components/input-number'
import { Route as DesignSystemComponentsInputDateRouteImport } from './routes/design-system/components/input-date'
import { Route as DesignSystemComponentsInputCheckboxGroupRouteImport } from './routes/design-system/components/input-checkbox-group'
import { Route as DesignSystemComponentsInputCheckboxCardRouteImport } from './routes/design-system/components/input-checkbox-card'
import { Route as DesignSystemComponentsInputCheckboxRouteImport } from './routes/design-system/components/input-checkbox'
import { Route as DesignSystemComponentsIndicatorRouteImport } from './routes/design-system/components/indicator'
import { Route as DesignSystemComponentsImageUploadRouteImport } from './routes/design-system/components/image-upload'
import { Route as DesignSystemComponentsIconButtonRouteImport } from './routes/design-system/components/icon-button'
import { Route as DesignSystemComponentsIconRouteImport } from './routes/design-system/components/icon'
import { Route as DesignSystemComponentsHighlightRouteImport } from './routes/design-system/components/highlight'
import { Route as DesignSystemComponentsFloatingPanelRouteImport } from './routes/design-system/components/floating-panel'
import { Route as DesignSystemComponentsFileUploadRouteImport } from './routes/design-system/components/file-upload'
import { Route as DesignSystemComponentsEmptyStateRouteImport } from './routes/design-system/components/empty-state'
import { Route as DesignSystemComponentsDrawerRouteImport } from './routes/design-system/components/drawer'
import { Route as DesignSystemComponentsDividerRouteImport } from './routes/design-system/components/divider'
import { Route as DesignSystemComponentsDataTableRouteImport } from './routes/design-system/components/data-table'
import { Route as DesignSystemComponentsButtonRouteImport } from './routes/design-system/components/button'
import { Route as DesignSystemComponentsBadgeRouteImport } from './routes/design-system/components/badge'
import { Route as DesignSystemComponentsAvatarRouteImport } from './routes/design-system/components/avatar'
import { Route as DesignSystemComponentsAlertRouteImport } from './routes/design-system/components/alert'
import { Route as DesignSystemComponentsAiIconRouteImport } from './routes/design-system/components/ai-icon'
import { Route as DesignSystemComponentsAccordionRouteImport } from './routes/design-system/components/accordion'
import { Route as AppMyAccountChar123SlugChar125RouteImport } from './routes/_app/my-account.{-$slug}'

const DesignSystemRouteRoute = DesignSystemRouteRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemIndexRoute = DesignSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DesignSystemTypographyRoute = DesignSystemTypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const DesignSystemColorsRoute = DesignSystemColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => DesignSystemRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPortalsRoute = AppPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFoldersRoute = AppFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => AppRouteRoute,
} as any)
const DesignSystemComponentsIndexRoute =
  DesignSystemComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsTreeRoute =
  DesignSystemComponentsTreeRouteImport.update({
    id: '/components/tree',
    path: '/components/tree',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsTourRoute =
  DesignSystemComponentsTourRouteImport.update({
    id: '/components/tour',
    path: '/components/tour',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsTooltipRoute =
  DesignSystemComponentsTooltipRouteImport.update({
    id: '/components/tooltip',
    path: '/components/tooltip',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsToastRoute =
  DesignSystemComponentsToastRouteImport.update({
    id: '/components/toast',
    path: '/components/toast',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsTimelineRoute =
  DesignSystemComponentsTimelineRouteImport.update({
    id: '/components/timeline',
    path: '/components/timeline',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsTabsRoute =
  DesignSystemComponentsTabsRouteImport.update({
    id: '/components/tabs',
    path: '/components/tabs',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsTableRoute =
  DesignSystemComponentsTableRouteImport.update({
    id: '/components/table',
    path: '/components/table',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsStepperRoute =
  DesignSystemComponentsStepperRouteImport.update({
    id: '/components/stepper',
    path: '/components/stepper',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsSliderRoute =
  DesignSystemComponentsSliderRouteImport.update({
    id: '/components/slider',
    path: '/components/slider',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsSignaturePadRoute =
  DesignSystemComponentsSignaturePadRouteImport.update({
    id: '/components/signature-pad',
    path: '/components/signature-pad',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsSegmentGroupRoute =
  DesignSystemComponentsSegmentGroupRouteImport.update({
    id: '/components/segment-group',
    path: '/components/segment-group',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsScrollAreaRoute =
  DesignSystemComponentsScrollAreaRouteImport.update({
    id: '/components/scroll-area',
    path: '/components/scroll-area',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsRatingRoute =
  DesignSystemComponentsRatingRouteImport.update({
    id: '/components/rating',
    path: '/components/rating',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsRangeSliderRoute =
  DesignSystemComponentsRangeSliderRouteImport.update({
    id: '/components/range-slider',
    path: '/components/range-slider',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsQrCodeRoute =
  DesignSystemComponentsQrCodeRouteImport.update({
    id: '/components/qr-code',
    path: '/components/qr-code',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsProgressSemiCircleRoute =
  DesignSystemComponentsProgressSemiCircleRouteImport.update({
    id: '/components/progress-semi-circle',
    path: '/components/progress-semi-circle',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsProgressCircleRoute =
  DesignSystemComponentsProgressCircleRouteImport.update({
    id: '/components/progress-circle',
    path: '/components/progress-circle',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsProgressRoute =
  DesignSystemComponentsProgressRouteImport.update({
    id: '/components/progress',
    path: '/components/progress',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsPopoverRoute =
  DesignSystemComponentsPopoverRouteImport.update({
    id: '/components/popover',
    path: '/components/popover',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsPaginationRoute =
  DesignSystemComponentsPaginationRouteImport.update({
    id: '/components/pagination',
    path: '/components/pagination',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsModalRoute =
  DesignSystemComponentsModalRouteImport.update({
    id: '/components/modal',
    path: '/components/modal',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsMenuRoute =
  DesignSystemComponentsMenuRouteImport.update({
    id: '/components/menu',
    path: '/components/menu',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputTimeRoute =
  DesignSystemComponentsInputTimeRouteImport.update({
    id: '/components/input-time',
    path: '/components/input-time',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputTextareaRoute =
  DesignSystemComponentsInputTextareaRouteImport.update({
    id: '/components/input-textarea',
    path: '/components/input-textarea',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputTextRoute =
  DesignSystemComponentsInputTextRouteImport.update({
    id: '/components/input-text',
    path: '/components/input-text',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputSwitchGroupRoute =
  DesignSystemComponentsInputSwitchGroupRouteImport.update({
    id: '/components/input-switch-group',
    path: '/components/input-switch-group',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputSwitchRoute =
  DesignSystemComponentsInputSwitchRouteImport.update({
    id: '/components/input-switch',
    path: '/components/input-switch',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputSelectMultipleRoute =
  DesignSystemComponentsInputSelectMultipleRouteImport.update({
    id: '/components/input-select-multiple',
    path: '/components/input-select-multiple',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputSelectRoute =
  DesignSystemComponentsInputSelectRouteImport.update({
    id: '/components/input-select',
    path: '/components/input-select',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputRadioGroupRoute =
  DesignSystemComponentsInputRadioGroupRouteImport.update({
    id: '/components/input-radio-group',
    path: '/components/input-radio-group',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputRadioCardRoute =
  DesignSystemComponentsInputRadioCardRouteImport.update({
    id: '/components/input-radio-card',
    path: '/components/input-radio-card',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputRadioRoute =
  DesignSystemComponentsInputRadioRouteImport.update({
    id: '/components/input-radio',
    path: '/components/input-radio',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputPinRoute =
  DesignSystemComponentsInputPinRouteImport.update({
    id: '/components/input-pin',
    path: '/components/input-pin',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputPasswordRoute =
  DesignSystemComponentsInputPasswordRouteImport.update({
    id: '/components/input-password',
    path: '/components/input-password',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputNumberRoute =
  DesignSystemComponentsInputNumberRouteImport.update({
    id: '/components/input-number',
    path: '/components/input-number',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputDateRoute =
  DesignSystemComponentsInputDateRouteImport.update({
    id: '/components/input-date',
    path: '/components/input-date',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputCheckboxGroupRoute =
  DesignSystemComponentsInputCheckboxGroupRouteImport.update({
    id: '/components/input-checkbox-group',
    path: '/components/input-checkbox-group',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputCheckboxCardRoute =
  DesignSystemComponentsInputCheckboxCardRouteImport.update({
    id: '/components/input-checkbox-card',
    path: '/components/input-checkbox-card',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsInputCheckboxRoute =
  DesignSystemComponentsInputCheckboxRouteImport.update({
    id: '/components/input-checkbox',
    path: '/components/input-checkbox',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsIndicatorRoute =
  DesignSystemComponentsIndicatorRouteImport.update({
    id: '/components/indicator',
    path: '/components/indicator',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsImageUploadRoute =
  DesignSystemComponentsImageUploadRouteImport.update({
    id: '/components/image-upload',
    path: '/components/image-upload',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsIconButtonRoute =
  DesignSystemComponentsIconButtonRouteImport.update({
    id: '/components/icon-button',
    path: '/components/icon-button',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsIconRoute =
  DesignSystemComponentsIconRouteImport.update({
    id: '/components/icon',
    path: '/components/icon',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsHighlightRoute =
  DesignSystemComponentsHighlightRouteImport.update({
    id: '/components/highlight',
    path: '/components/highlight',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsFloatingPanelRoute =
  DesignSystemComponentsFloatingPanelRouteImport.update({
    id: '/components/floating-panel',
    path: '/components/floating-panel',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsFileUploadRoute =
  DesignSystemComponentsFileUploadRouteImport.update({
    id: '/components/file-upload',
    path: '/components/file-upload',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsEmptyStateRoute =
  DesignSystemComponentsEmptyStateRouteImport.update({
    id: '/components/empty-state',
    path: '/components/empty-state',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsDrawerRoute =
  DesignSystemComponentsDrawerRouteImport.update({
    id: '/components/drawer',
    path: '/components/drawer',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsDividerRoute =
  DesignSystemComponentsDividerRouteImport.update({
    id: '/components/divider',
    path: '/components/divider',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsDataTableRoute =
  DesignSystemComponentsDataTableRouteImport.update({
    id: '/components/data-table',
    path: '/components/data-table',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsButtonRoute =
  DesignSystemComponentsButtonRouteImport.update({
    id: '/components/button',
    path: '/components/button',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsBadgeRoute =
  DesignSystemComponentsBadgeRouteImport.update({
    id: '/components/badge',
    path: '/components/badge',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsAvatarRoute =
  DesignSystemComponentsAvatarRouteImport.update({
    id: '/components/avatar',
    path: '/components/avatar',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsAlertRoute =
  DesignSystemComponentsAlertRouteImport.update({
    id: '/components/alert',
    path: '/components/alert',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsAiIconRoute =
  DesignSystemComponentsAiIconRouteImport.update({
    id: '/components/ai-icon',
    path: '/components/ai-icon',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const DesignSystemComponentsAccordionRoute =
  DesignSystemComponentsAccordionRouteImport.update({
    id: '/components/accordion',
    path: '/components/accordion',
    getParentRoute: () => DesignSystemRouteRoute,
  } as any)
const AppMyAccountChar123SlugChar125Route =
  AppMyAccountChar123SlugChar125RouteImport.update({
    id: '/my-account/{-$slug}',
    path: '/my-account/{-$slug}',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/design-system': typeof DesignSystemRouteRouteWithChildren
  '/folders': typeof AppFoldersRoute
  '/forms': typeof AppFormsRoute
  '/portals': typeof AppPortalsRoute
  '/requests': typeof AppRequestsRoute
  '/tasks': typeof AppTasksRoute
  '/workflows': typeof AppWorkflowsRoute
  '/login': typeof AuthLoginRoute
  '/sign-in': typeof AuthSignInRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/design-system/': typeof DesignSystemIndexRoute
  '/my-account/{-$slug}': typeof AppMyAccountChar123SlugChar125Route
  '/design-system/components/accordion': typeof DesignSystemComponentsAccordionRoute
  '/design-system/components/ai-icon': typeof DesignSystemComponentsAiIconRoute
  '/design-system/components/alert': typeof DesignSystemComponentsAlertRoute
  '/design-system/components/avatar': typeof DesignSystemComponentsAvatarRoute
  '/design-system/components/badge': typeof DesignSystemComponentsBadgeRoute
  '/design-system/components/button': typeof DesignSystemComponentsButtonRoute
  '/design-system/components/data-table': typeof DesignSystemComponentsDataTableRoute
  '/design-system/components/divider': typeof DesignSystemComponentsDividerRoute
  '/design-system/components/drawer': typeof DesignSystemComponentsDrawerRoute
  '/design-system/components/empty-state': typeof DesignSystemComponentsEmptyStateRoute
  '/design-system/components/file-upload': typeof DesignSystemComponentsFileUploadRoute
  '/design-system/components/floating-panel': typeof DesignSystemComponentsFloatingPanelRoute
  '/design-system/components/highlight': typeof DesignSystemComponentsHighlightRoute
  '/design-system/components/icon': typeof DesignSystemComponentsIconRoute
  '/design-system/components/icon-button': typeof DesignSystemComponentsIconButtonRoute
  '/design-system/components/image-upload': typeof DesignSystemComponentsImageUploadRoute
  '/design-system/components/indicator': typeof DesignSystemComponentsIndicatorRoute
  '/design-system/components/input-checkbox': typeof DesignSystemComponentsInputCheckboxRoute
  '/design-system/components/input-checkbox-card': typeof DesignSystemComponentsInputCheckboxCardRoute
  '/design-system/components/input-checkbox-group': typeof DesignSystemComponentsInputCheckboxGroupRoute
  '/design-system/components/input-date': typeof DesignSystemComponentsInputDateRoute
  '/design-system/components/input-number': typeof DesignSystemComponentsInputNumberRoute
  '/design-system/components/input-password': typeof DesignSystemComponentsInputPasswordRoute
  '/design-system/components/input-pin': typeof DesignSystemComponentsInputPinRoute
  '/design-system/components/input-radio': typeof DesignSystemComponentsInputRadioRoute
  '/design-system/components/input-radio-card': typeof DesignSystemComponentsInputRadioCardRoute
  '/design-system/components/input-radio-group': typeof DesignSystemComponentsInputRadioGroupRoute
  '/design-system/components/input-select': typeof DesignSystemComponentsInputSelectRoute
  '/design-system/components/input-select-multiple': typeof DesignSystemComponentsInputSelectMultipleRoute
  '/design-system/components/input-switch': typeof DesignSystemComponentsInputSwitchRoute
  '/design-system/components/input-switch-group': typeof DesignSystemComponentsInputSwitchGroupRoute
  '/design-system/components/input-text': typeof DesignSystemComponentsInputTextRoute
  '/design-system/components/input-textarea': typeof DesignSystemComponentsInputTextareaRoute
  '/design-system/components/input-time': typeof DesignSystemComponentsInputTimeRoute
  '/design-system/components/menu': typeof DesignSystemComponentsMenuRoute
  '/design-system/components/modal': typeof DesignSystemComponentsModalRoute
  '/design-system/components/pagination': typeof DesignSystemComponentsPaginationRoute
  '/design-system/components/popover': typeof DesignSystemComponentsPopoverRoute
  '/design-system/components/progress': typeof DesignSystemComponentsProgressRoute
  '/design-system/components/progress-circle': typeof DesignSystemComponentsProgressCircleRoute
  '/design-system/components/progress-semi-circle': typeof DesignSystemComponentsProgressSemiCircleRoute
  '/design-system/components/qr-code': typeof DesignSystemComponentsQrCodeRoute
  '/design-system/components/range-slider': typeof DesignSystemComponentsRangeSliderRoute
  '/design-system/components/rating': typeof DesignSystemComponentsRatingRoute
  '/design-system/components/scroll-area': typeof DesignSystemComponentsScrollAreaRoute
  '/design-system/components/segment-group': typeof DesignSystemComponentsSegmentGroupRoute
  '/design-system/components/signature-pad': typeof DesignSystemComponentsSignaturePadRoute
  '/design-system/components/slider': typeof DesignSystemComponentsSliderRoute
  '/design-system/components/stepper': typeof DesignSystemComponentsStepperRoute
  '/design-system/components/table': typeof DesignSystemComponentsTableRoute
  '/design-system/components/tabs': typeof DesignSystemComponentsTabsRoute
  '/design-system/components/timeline': typeof DesignSystemComponentsTimelineRoute
  '/design-system/components/toast': typeof DesignSystemComponentsToastRoute
  '/design-system/components/tooltip': typeof DesignSystemComponentsTooltipRoute
  '/design-system/components/tour': typeof DesignSystemComponentsTourRoute
  '/design-system/components/tree': typeof DesignSystemComponentsTreeRoute
  '/design-system/components/': typeof DesignSystemComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/folders': typeof AppFoldersRoute
  '/forms': typeof AppFormsRoute
  '/portals': typeof AppPortalsRoute
  '/requests': typeof AppRequestsRoute
  '/tasks': typeof AppTasksRoute
  '/workflows': typeof AppWorkflowsRoute
  '/login': typeof AuthLoginRoute
  '/sign-in': typeof AuthSignInRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/': typeof AppIndexRoute
  '/design-system': typeof DesignSystemIndexRoute
  '/my-account/{-$slug}': typeof AppMyAccountChar123SlugChar125Route
  '/design-system/components/accordion': typeof DesignSystemComponentsAccordionRoute
  '/design-system/components/ai-icon': typeof DesignSystemComponentsAiIconRoute
  '/design-system/components/alert': typeof DesignSystemComponentsAlertRoute
  '/design-system/components/avatar': typeof DesignSystemComponentsAvatarRoute
  '/design-system/components/badge': typeof DesignSystemComponentsBadgeRoute
  '/design-system/components/button': typeof DesignSystemComponentsButtonRoute
  '/design-system/components/data-table': typeof DesignSystemComponentsDataTableRoute
  '/design-system/components/divider': typeof DesignSystemComponentsDividerRoute
  '/design-system/components/drawer': typeof DesignSystemComponentsDrawerRoute
  '/design-system/components/empty-state': typeof DesignSystemComponentsEmptyStateRoute
  '/design-system/components/file-upload': typeof DesignSystemComponentsFileUploadRoute
  '/design-system/components/floating-panel': typeof DesignSystemComponentsFloatingPanelRoute
  '/design-system/components/highlight': typeof DesignSystemComponentsHighlightRoute
  '/design-system/components/icon': typeof DesignSystemComponentsIconRoute
  '/design-system/components/icon-button': typeof DesignSystemComponentsIconButtonRoute
  '/design-system/components/image-upload': typeof DesignSystemComponentsImageUploadRoute
  '/design-system/components/indicator': typeof DesignSystemComponentsIndicatorRoute
  '/design-system/components/input-checkbox': typeof DesignSystemComponentsInputCheckboxRoute
  '/design-system/components/input-checkbox-card': typeof DesignSystemComponentsInputCheckboxCardRoute
  '/design-system/components/input-checkbox-group': typeof DesignSystemComponentsInputCheckboxGroupRoute
  '/design-system/components/input-date': typeof DesignSystemComponentsInputDateRoute
  '/design-system/components/input-number': typeof DesignSystemComponentsInputNumberRoute
  '/design-system/components/input-password': typeof DesignSystemComponentsInputPasswordRoute
  '/design-system/components/input-pin': typeof DesignSystemComponentsInputPinRoute
  '/design-system/components/input-radio': typeof DesignSystemComponentsInputRadioRoute
  '/design-system/components/input-radio-card': typeof DesignSystemComponentsInputRadioCardRoute
  '/design-system/components/input-radio-group': typeof DesignSystemComponentsInputRadioGroupRoute
  '/design-system/components/input-select': typeof DesignSystemComponentsInputSelectRoute
  '/design-system/components/input-select-multiple': typeof DesignSystemComponentsInputSelectMultipleRoute
  '/design-system/components/input-switch': typeof DesignSystemComponentsInputSwitchRoute
  '/design-system/components/input-switch-group': typeof DesignSystemComponentsInputSwitchGroupRoute
  '/design-system/components/input-text': typeof DesignSystemComponentsInputTextRoute
  '/design-system/components/input-textarea': typeof DesignSystemComponentsInputTextareaRoute
  '/design-system/components/input-time': typeof DesignSystemComponentsInputTimeRoute
  '/design-system/components/menu': typeof DesignSystemComponentsMenuRoute
  '/design-system/components/modal': typeof DesignSystemComponentsModalRoute
  '/design-system/components/pagination': typeof DesignSystemComponentsPaginationRoute
  '/design-system/components/popover': typeof DesignSystemComponentsPopoverRoute
  '/design-system/components/progress': typeof DesignSystemComponentsProgressRoute
  '/design-system/components/progress-circle': typeof DesignSystemComponentsProgressCircleRoute
  '/design-system/components/progress-semi-circle': typeof DesignSystemComponentsProgressSemiCircleRoute
  '/design-system/components/qr-code': typeof DesignSystemComponentsQrCodeRoute
  '/design-system/components/range-slider': typeof DesignSystemComponentsRangeSliderRoute
  '/design-system/components/rating': typeof DesignSystemComponentsRatingRoute
  '/design-system/components/scroll-area': typeof DesignSystemComponentsScrollAreaRoute
  '/design-system/components/segment-group': typeof DesignSystemComponentsSegmentGroupRoute
  '/design-system/components/signature-pad': typeof DesignSystemComponentsSignaturePadRoute
  '/design-system/components/slider': typeof DesignSystemComponentsSliderRoute
  '/design-system/components/stepper': typeof DesignSystemComponentsStepperRoute
  '/design-system/components/table': typeof DesignSystemComponentsTableRoute
  '/design-system/components/tabs': typeof DesignSystemComponentsTabsRoute
  '/design-system/components/timeline': typeof DesignSystemComponentsTimelineRoute
  '/design-system/components/toast': typeof DesignSystemComponentsToastRoute
  '/design-system/components/tooltip': typeof DesignSystemComponentsTooltipRoute
  '/design-system/components/tour': typeof DesignSystemComponentsTourRoute
  '/design-system/components/tree': typeof DesignSystemComponentsTreeRoute
  '/design-system/components': typeof DesignSystemComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/design-system': typeof DesignSystemRouteRouteWithChildren
  '/_app/folders': typeof AppFoldersRoute
  '/_app/forms': typeof AppFormsRoute
  '/_app/portals': typeof AppPortalsRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/workflows': typeof AppWorkflowsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/design-system/colors': typeof DesignSystemColorsRoute
  '/design-system/typography': typeof DesignSystemTypographyRoute
  '/_app/': typeof AppIndexRoute
  '/design-system/': typeof DesignSystemIndexRoute
  '/_app/my-account/{-$slug}': typeof AppMyAccountChar123SlugChar125Route
  '/design-system/components/accordion': typeof DesignSystemComponentsAccordionRoute
  '/design-system/components/ai-icon': typeof DesignSystemComponentsAiIconRoute
  '/design-system/components/alert': typeof DesignSystemComponentsAlertRoute
  '/design-system/components/avatar': typeof DesignSystemComponentsAvatarRoute
  '/design-system/components/badge': typeof DesignSystemComponentsBadgeRoute
  '/design-system/components/button': typeof DesignSystemComponentsButtonRoute
  '/design-system/components/data-table': typeof DesignSystemComponentsDataTableRoute
  '/design-system/components/divider': typeof DesignSystemComponentsDividerRoute
  '/design-system/components/drawer': typeof DesignSystemComponentsDrawerRoute
  '/design-system/components/empty-state': typeof DesignSystemComponentsEmptyStateRoute
  '/design-system/components/file-upload': typeof DesignSystemComponentsFileUploadRoute
  '/design-system/components/floating-panel': typeof DesignSystemComponentsFloatingPanelRoute
  '/design-system/components/highlight': typeof DesignSystemComponentsHighlightRoute
  '/design-system/components/icon': typeof DesignSystemComponentsIconRoute
  '/design-system/components/icon-button': typeof DesignSystemComponentsIconButtonRoute
  '/design-system/components/image-upload': typeof DesignSystemComponentsImageUploadRoute
  '/design-system/components/indicator': typeof DesignSystemComponentsIndicatorRoute
  '/design-system/components/input-checkbox': typeof DesignSystemComponentsInputCheckboxRoute
  '/design-system/components/input-checkbox-card': typeof DesignSystemComponentsInputCheckboxCardRoute
  '/design-system/components/input-checkbox-group': typeof DesignSystemComponentsInputCheckboxGroupRoute
  '/design-system/components/input-date': typeof DesignSystemComponentsInputDateRoute
  '/design-system/components/input-number': typeof DesignSystemComponentsInputNumberRoute
  '/design-system/components/input-password': typeof DesignSystemComponentsInputPasswordRoute
  '/design-system/components/input-pin': typeof DesignSystemComponentsInputPinRoute
  '/design-system/components/input-radio': typeof DesignSystemComponentsInputRadioRoute
  '/design-system/components/input-radio-card': typeof DesignSystemComponentsInputRadioCardRoute
  '/design-system/components/input-radio-group': typeof DesignSystemComponentsInputRadioGroupRoute
  '/design-system/components/input-select': typeof DesignSystemComponentsInputSelectRoute
  '/design-system/components/input-select-multiple': typeof DesignSystemComponentsInputSelectMultipleRoute
  '/design-system/components/input-switch': typeof DesignSystemComponentsInputSwitchRoute
  '/design-system/components/input-switch-group': typeof DesignSystemComponentsInputSwitchGroupRoute
  '/design-system/components/input-text': typeof DesignSystemComponentsInputTextRoute
  '/design-system/components/input-textarea': typeof DesignSystemComponentsInputTextareaRoute
  '/design-system/components/input-time': typeof DesignSystemComponentsInputTimeRoute
  '/design-system/components/menu': typeof DesignSystemComponentsMenuRoute
  '/design-system/components/modal': typeof DesignSystemComponentsModalRoute
  '/design-system/components/pagination': typeof DesignSystemComponentsPaginationRoute
  '/design-system/components/popover': typeof DesignSystemComponentsPopoverRoute
  '/design-system/components/progress': typeof DesignSystemComponentsProgressRoute
  '/design-system/components/progress-circle': typeof DesignSystemComponentsProgressCircleRoute
  '/design-system/components/progress-semi-circle': typeof DesignSystemComponentsProgressSemiCircleRoute
  '/design-system/components/qr-code': typeof DesignSystemComponentsQrCodeRoute
  '/design-system/components/range-slider': typeof DesignSystemComponentsRangeSliderRoute
  '/design-system/components/rating': typeof DesignSystemComponentsRatingRoute
  '/design-system/components/scroll-area': typeof DesignSystemComponentsScrollAreaRoute
  '/design-system/components/segment-group': typeof DesignSystemComponentsSegmentGroupRoute
  '/design-system/components/signature-pad': typeof DesignSystemComponentsSignaturePadRoute
  '/design-system/components/slider': typeof DesignSystemComponentsSliderRoute
  '/design-system/components/stepper': typeof DesignSystemComponentsStepperRoute
  '/design-system/components/table': typeof DesignSystemComponentsTableRoute
  '/design-system/components/tabs': typeof DesignSystemComponentsTabsRoute
  '/design-system/components/timeline': typeof DesignSystemComponentsTimelineRoute
  '/design-system/components/toast': typeof DesignSystemComponentsToastRoute
  '/design-system/components/tooltip': typeof DesignSystemComponentsTooltipRoute
  '/design-system/components/tour': typeof DesignSystemComponentsTourRoute
  '/design-system/components/tree': typeof DesignSystemComponentsTreeRoute
  '/design-system/components/': typeof DesignSystemComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/folders'
    | '/forms'
    | '/portals'
    | '/requests'
    | '/tasks'
    | '/workflows'
    | '/login'
    | '/sign-in'
    | '/design-system/colors'
    | '/design-system/typography'
    | '/design-system/'
    | '/my-account/{-$slug}'
    | '/design-system/components/accordion'
    | '/design-system/components/ai-icon'
    | '/design-system/components/alert'
    | '/design-system/components/avatar'
    | '/design-system/components/badge'
    | '/design-system/components/button'
    | '/design-system/components/data-table'
    | '/design-system/components/divider'
    | '/design-system/components/drawer'
    | '/design-system/components/empty-state'
    | '/design-system/components/file-upload'
    | '/design-system/components/floating-panel'
    | '/design-system/components/highlight'
    | '/design-system/components/icon'
    | '/design-system/components/icon-button'
    | '/design-system/components/image-upload'
    | '/design-system/components/indicator'
    | '/design-system/components/input-checkbox'
    | '/design-system/components/input-checkbox-card'
    | '/design-system/components/input-checkbox-group'
    | '/design-system/components/input-date'
    | '/design-system/components/input-number'
    | '/design-system/components/input-password'
    | '/design-system/components/input-pin'
    | '/design-system/components/input-radio'
    | '/design-system/components/input-radio-card'
    | '/design-system/components/input-radio-group'
    | '/design-system/components/input-select'
    | '/design-system/components/input-select-multiple'
    | '/design-system/components/input-switch'
    | '/design-system/components/input-switch-group'
    | '/design-system/components/input-text'
    | '/design-system/components/input-textarea'
    | '/design-system/components/input-time'
    | '/design-system/components/menu'
    | '/design-system/components/modal'
    | '/design-system/components/pagination'
    | '/design-system/components/popover'
    | '/design-system/components/progress'
    | '/design-system/components/progress-circle'
    | '/design-system/components/progress-semi-circle'
    | '/design-system/components/qr-code'
    | '/design-system/components/range-slider'
    | '/design-system/components/rating'
    | '/design-system/components/scroll-area'
    | '/design-system/components/segment-group'
    | '/design-system/components/signature-pad'
    | '/design-system/components/slider'
    | '/design-system/components/stepper'
    | '/design-system/components/table'
    | '/design-system/components/tabs'
    | '/design-system/components/timeline'
    | '/design-system/components/toast'
    | '/design-system/components/tooltip'
    | '/design-system/components/tour'
    | '/design-system/components/tree'
    | '/design-system/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/folders'
    | '/forms'
    | '/portals'
    | '/requests'
    | '/tasks'
    | '/workflows'
    | '/login'
    | '/sign-in'
    | '/design-system/colors'
    | '/design-system/typography'
    | '/'
    | '/design-system'
    | '/my-account/{-$slug}'
    | '/design-system/components/accordion'
    | '/design-system/components/ai-icon'
    | '/design-system/components/alert'
    | '/design-system/components/avatar'
    | '/design-system/components/badge'
    | '/design-system/components/button'
    | '/design-system/components/data-table'
    | '/design-system/components/divider'
    | '/design-system/components/drawer'
    | '/design-system/components/empty-state'
    | '/design-system/components/file-upload'
    | '/design-system/components/floating-panel'
    | '/design-system/components/highlight'
    | '/design-system/components/icon'
    | '/design-system/components/icon-button'
    | '/design-system/components/image-upload'
    | '/design-system/components/indicator'
    | '/design-system/components/input-checkbox'
    | '/design-system/components/input-checkbox-card'
    | '/design-system/components/input-checkbox-group'
    | '/design-system/components/input-date'
    | '/design-system/components/input-number'
    | '/design-system/components/input-password'
    | '/design-system/components/input-pin'
    | '/design-system/components/input-radio'
    | '/design-system/components/input-radio-card'
    | '/design-system/components/input-radio-group'
    | '/design-system/components/input-select'
    | '/design-system/components/input-select-multiple'
    | '/design-system/components/input-switch'
    | '/design-system/components/input-switch-group'
    | '/design-system/components/input-text'
    | '/design-system/components/input-textarea'
    | '/design-system/components/input-time'
    | '/design-system/components/menu'
    | '/design-system/components/modal'
    | '/design-system/components/pagination'
    | '/design-system/components/popover'
    | '/design-system/components/progress'
    | '/design-system/components/progress-circle'
    | '/design-system/components/progress-semi-circle'
    | '/design-system/components/qr-code'
    | '/design-system/components/range-slider'
    | '/design-system/components/rating'
    | '/design-system/components/scroll-area'
    | '/design-system/components/segment-group'
    | '/design-system/components/signature-pad'
    | '/design-system/components/slider'
    | '/design-system/components/stepper'
    | '/design-system/components/table'
    | '/design-system/components/tabs'
    | '/design-system/components/timeline'
    | '/design-system/components/toast'
    | '/design-system/components/tooltip'
    | '/design-system/components/tour'
    | '/design-system/components/tree'
    | '/design-system/components'
  id:
    | '__root__'
    | '/_app'
    | '/design-system'
    | '/_app/folders'
    | '/_app/forms'
    | '/_app/portals'
    | '/_app/requests'
    | '/_app/tasks'
    | '/_app/workflows'
    | '/_auth/login'
    | '/_auth/sign-in'
    | '/design-system/colors'
    | '/design-system/typography'
    | '/_app/'
    | '/design-system/'
    | '/_app/my-account/{-$slug}'
    | '/design-system/components/accordion'
    | '/design-system/components/ai-icon'
    | '/design-system/components/alert'
    | '/design-system/components/avatar'
    | '/design-system/components/badge'
    | '/design-system/components/button'
    | '/design-system/components/data-table'
    | '/design-system/components/divider'
    | '/design-system/components/drawer'
    | '/design-system/components/empty-state'
    | '/design-system/components/file-upload'
    | '/design-system/components/floating-panel'
    | '/design-system/components/highlight'
    | '/design-system/components/icon'
    | '/design-system/components/icon-button'
    | '/design-system/components/image-upload'
    | '/design-system/components/indicator'
    | '/design-system/components/input-checkbox'
    | '/design-system/components/input-checkbox-card'
    | '/design-system/components/input-checkbox-group'
    | '/design-system/components/input-date'
    | '/design-system/components/input-number'
    | '/design-system/components/input-password'
    | '/design-system/components/input-pin'
    | '/design-system/components/input-radio'
    | '/design-system/components/input-radio-card'
    | '/design-system/components/input-radio-group'
    | '/design-system/components/input-select'
    | '/design-system/components/input-select-multiple'
    | '/design-system/components/input-switch'
    | '/design-system/components/input-switch-group'
    | '/design-system/components/input-text'
    | '/design-system/components/input-textarea'
    | '/design-system/components/input-time'
    | '/design-system/components/menu'
    | '/design-system/components/modal'
    | '/design-system/components/pagination'
    | '/design-system/components/popover'
    | '/design-system/components/progress'
    | '/design-system/components/progress-circle'
    | '/design-system/components/progress-semi-circle'
    | '/design-system/components/qr-code'
    | '/design-system/components/range-slider'
    | '/design-system/components/rating'
    | '/design-system/components/scroll-area'
    | '/design-system/components/segment-group'
    | '/design-system/components/signature-pad'
    | '/design-system/components/slider'
    | '/design-system/components/stepper'
    | '/design-system/components/table'
    | '/design-system/components/tabs'
    | '/design-system/components/timeline'
    | '/design-system/components/toast'
    | '/design-system/components/tooltip'
    | '/design-system/components/tour'
    | '/design-system/components/tree'
    | '/design-system/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DesignSystemRouteRoute: typeof DesignSystemRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system/': {
      id: '/design-system/'
      path: '/'
      fullPath: '/design-system/'
      preLoaderRoute: typeof DesignSystemIndexRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/design-system/typography': {
      id: '/design-system/typography'
      path: '/typography'
      fullPath: '/design-system/typography'
      preLoaderRoute: typeof DesignSystemTypographyRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/colors': {
      id: '/design-system/colors'
      path: '/colors'
      fullPath: '/design-system/colors'
      preLoaderRoute: typeof DesignSystemColorsRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/portals': {
      id: '/_app/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof AppPortalsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/folders': {
      id: '/_app/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AppFoldersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/design-system/components/': {
      id: '/design-system/components/'
      path: '/components'
      fullPath: '/design-system/components/'
      preLoaderRoute: typeof DesignSystemComponentsIndexRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/tree': {
      id: '/design-system/components/tree'
      path: '/components/tree'
      fullPath: '/design-system/components/tree'
      preLoaderRoute: typeof DesignSystemComponentsTreeRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/tour': {
      id: '/design-system/components/tour'
      path: '/components/tour'
      fullPath: '/design-system/components/tour'
      preLoaderRoute: typeof DesignSystemComponentsTourRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/tooltip': {
      id: '/design-system/components/tooltip'
      path: '/components/tooltip'
      fullPath: '/design-system/components/tooltip'
      preLoaderRoute: typeof DesignSystemComponentsTooltipRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/toast': {
      id: '/design-system/components/toast'
      path: '/components/toast'
      fullPath: '/design-system/components/toast'
      preLoaderRoute: typeof DesignSystemComponentsToastRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/timeline': {
      id: '/design-system/components/timeline'
      path: '/components/timeline'
      fullPath: '/design-system/components/timeline'
      preLoaderRoute: typeof DesignSystemComponentsTimelineRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/tabs': {
      id: '/design-system/components/tabs'
      path: '/components/tabs'
      fullPath: '/design-system/components/tabs'
      preLoaderRoute: typeof DesignSystemComponentsTabsRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/table': {
      id: '/design-system/components/table'
      path: '/components/table'
      fullPath: '/design-system/components/table'
      preLoaderRoute: typeof DesignSystemComponentsTableRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/stepper': {
      id: '/design-system/components/stepper'
      path: '/components/stepper'
      fullPath: '/design-system/components/stepper'
      preLoaderRoute: typeof DesignSystemComponentsStepperRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/slider': {
      id: '/design-system/components/slider'
      path: '/components/slider'
      fullPath: '/design-system/components/slider'
      preLoaderRoute: typeof DesignSystemComponentsSliderRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/signature-pad': {
      id: '/design-system/components/signature-pad'
      path: '/components/signature-pad'
      fullPath: '/design-system/components/signature-pad'
      preLoaderRoute: typeof DesignSystemComponentsSignaturePadRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/segment-group': {
      id: '/design-system/components/segment-group'
      path: '/components/segment-group'
      fullPath: '/design-system/components/segment-group'
      preLoaderRoute: typeof DesignSystemComponentsSegmentGroupRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/scroll-area': {
      id: '/design-system/components/scroll-area'
      path: '/components/scroll-area'
      fullPath: '/design-system/components/scroll-area'
      preLoaderRoute: typeof DesignSystemComponentsScrollAreaRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/rating': {
      id: '/design-system/components/rating'
      path: '/components/rating'
      fullPath: '/design-system/components/rating'
      preLoaderRoute: typeof DesignSystemComponentsRatingRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/range-slider': {
      id: '/design-system/components/range-slider'
      path: '/components/range-slider'
      fullPath: '/design-system/components/range-slider'
      preLoaderRoute: typeof DesignSystemComponentsRangeSliderRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/qr-code': {
      id: '/design-system/components/qr-code'
      path: '/components/qr-code'
      fullPath: '/design-system/components/qr-code'
      preLoaderRoute: typeof DesignSystemComponentsQrCodeRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/progress-semi-circle': {
      id: '/design-system/components/progress-semi-circle'
      path: '/components/progress-semi-circle'
      fullPath: '/design-system/components/progress-semi-circle'
      preLoaderRoute: typeof DesignSystemComponentsProgressSemiCircleRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/progress-circle': {
      id: '/design-system/components/progress-circle'
      path: '/components/progress-circle'
      fullPath: '/design-system/components/progress-circle'
      preLoaderRoute: typeof DesignSystemComponentsProgressCircleRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/progress': {
      id: '/design-system/components/progress'
      path: '/components/progress'
      fullPath: '/design-system/components/progress'
      preLoaderRoute: typeof DesignSystemComponentsProgressRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/popover': {
      id: '/design-system/components/popover'
      path: '/components/popover'
      fullPath: '/design-system/components/popover'
      preLoaderRoute: typeof DesignSystemComponentsPopoverRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/pagination': {
      id: '/design-system/components/pagination'
      path: '/components/pagination'
      fullPath: '/design-system/components/pagination'
      preLoaderRoute: typeof DesignSystemComponentsPaginationRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/modal': {
      id: '/design-system/components/modal'
      path: '/components/modal'
      fullPath: '/design-system/components/modal'
      preLoaderRoute: typeof DesignSystemComponentsModalRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/menu': {
      id: '/design-system/components/menu'
      path: '/components/menu'
      fullPath: '/design-system/components/menu'
      preLoaderRoute: typeof DesignSystemComponentsMenuRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-time': {
      id: '/design-system/components/input-time'
      path: '/components/input-time'
      fullPath: '/design-system/components/input-time'
      preLoaderRoute: typeof DesignSystemComponentsInputTimeRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-textarea': {
      id: '/design-system/components/input-textarea'
      path: '/components/input-textarea'
      fullPath: '/design-system/components/input-textarea'
      preLoaderRoute: typeof DesignSystemComponentsInputTextareaRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-text': {
      id: '/design-system/components/input-text'
      path: '/components/input-text'
      fullPath: '/design-system/components/input-text'
      preLoaderRoute: typeof DesignSystemComponentsInputTextRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-switch-group': {
      id: '/design-system/components/input-switch-group'
      path: '/components/input-switch-group'
      fullPath: '/design-system/components/input-switch-group'
      preLoaderRoute: typeof DesignSystemComponentsInputSwitchGroupRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-switch': {
      id: '/design-system/components/input-switch'
      path: '/components/input-switch'
      fullPath: '/design-system/components/input-switch'
      preLoaderRoute: typeof DesignSystemComponentsInputSwitchRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-select-multiple': {
      id: '/design-system/components/input-select-multiple'
      path: '/components/input-select-multiple'
      fullPath: '/design-system/components/input-select-multiple'
      preLoaderRoute: typeof DesignSystemComponentsInputSelectMultipleRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-select': {
      id: '/design-system/components/input-select'
      path: '/components/input-select'
      fullPath: '/design-system/components/input-select'
      preLoaderRoute: typeof DesignSystemComponentsInputSelectRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-radio-group': {
      id: '/design-system/components/input-radio-group'
      path: '/components/input-radio-group'
      fullPath: '/design-system/components/input-radio-group'
      preLoaderRoute: typeof DesignSystemComponentsInputRadioGroupRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-radio-card': {
      id: '/design-system/components/input-radio-card'
      path: '/components/input-radio-card'
      fullPath: '/design-system/components/input-radio-card'
      preLoaderRoute: typeof DesignSystemComponentsInputRadioCardRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-radio': {
      id: '/design-system/components/input-radio'
      path: '/components/input-radio'
      fullPath: '/design-system/components/input-radio'
      preLoaderRoute: typeof DesignSystemComponentsInputRadioRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-pin': {
      id: '/design-system/components/input-pin'
      path: '/components/input-pin'
      fullPath: '/design-system/components/input-pin'
      preLoaderRoute: typeof DesignSystemComponentsInputPinRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-password': {
      id: '/design-system/components/input-password'
      path: '/components/input-password'
      fullPath: '/design-system/components/input-password'
      preLoaderRoute: typeof DesignSystemComponentsInputPasswordRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-number': {
      id: '/design-system/components/input-number'
      path: '/components/input-number'
      fullPath: '/design-system/components/input-number'
      preLoaderRoute: typeof DesignSystemComponentsInputNumberRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-date': {
      id: '/design-system/components/input-date'
      path: '/components/input-date'
      fullPath: '/design-system/components/input-date'
      preLoaderRoute: typeof DesignSystemComponentsInputDateRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-checkbox-group': {
      id: '/design-system/components/input-checkbox-group'
      path: '/components/input-checkbox-group'
      fullPath: '/design-system/components/input-checkbox-group'
      preLoaderRoute: typeof DesignSystemComponentsInputCheckboxGroupRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-checkbox-card': {
      id: '/design-system/components/input-checkbox-card'
      path: '/components/input-checkbox-card'
      fullPath: '/design-system/components/input-checkbox-card'
      preLoaderRoute: typeof DesignSystemComponentsInputCheckboxCardRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/input-checkbox': {
      id: '/design-system/components/input-checkbox'
      path: '/components/input-checkbox'
      fullPath: '/design-system/components/input-checkbox'
      preLoaderRoute: typeof DesignSystemComponentsInputCheckboxRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/indicator': {
      id: '/design-system/components/indicator'
      path: '/components/indicator'
      fullPath: '/design-system/components/indicator'
      preLoaderRoute: typeof DesignSystemComponentsIndicatorRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/image-upload': {
      id: '/design-system/components/image-upload'
      path: '/components/image-upload'
      fullPath: '/design-system/components/image-upload'
      preLoaderRoute: typeof DesignSystemComponentsImageUploadRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/icon-button': {
      id: '/design-system/components/icon-button'
      path: '/components/icon-button'
      fullPath: '/design-system/components/icon-button'
      preLoaderRoute: typeof DesignSystemComponentsIconButtonRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/icon': {
      id: '/design-system/components/icon'
      path: '/components/icon'
      fullPath: '/design-system/components/icon'
      preLoaderRoute: typeof DesignSystemComponentsIconRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/highlight': {
      id: '/design-system/components/highlight'
      path: '/components/highlight'
      fullPath: '/design-system/components/highlight'
      preLoaderRoute: typeof DesignSystemComponentsHighlightRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/floating-panel': {
      id: '/design-system/components/floating-panel'
      path: '/components/floating-panel'
      fullPath: '/design-system/components/floating-panel'
      preLoaderRoute: typeof DesignSystemComponentsFloatingPanelRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/file-upload': {
      id: '/design-system/components/file-upload'
      path: '/components/file-upload'
      fullPath: '/design-system/components/file-upload'
      preLoaderRoute: typeof DesignSystemComponentsFileUploadRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/empty-state': {
      id: '/design-system/components/empty-state'
      path: '/components/empty-state'
      fullPath: '/design-system/components/empty-state'
      preLoaderRoute: typeof DesignSystemComponentsEmptyStateRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/drawer': {
      id: '/design-system/components/drawer'
      path: '/components/drawer'
      fullPath: '/design-system/components/drawer'
      preLoaderRoute: typeof DesignSystemComponentsDrawerRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/divider': {
      id: '/design-system/components/divider'
      path: '/components/divider'
      fullPath: '/design-system/components/divider'
      preLoaderRoute: typeof DesignSystemComponentsDividerRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/data-table': {
      id: '/design-system/components/data-table'
      path: '/components/data-table'
      fullPath: '/design-system/components/data-table'
      preLoaderRoute: typeof DesignSystemComponentsDataTableRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/button': {
      id: '/design-system/components/button'
      path: '/components/button'
      fullPath: '/design-system/components/button'
      preLoaderRoute: typeof DesignSystemComponentsButtonRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/badge': {
      id: '/design-system/components/badge'
      path: '/components/badge'
      fullPath: '/design-system/components/badge'
      preLoaderRoute: typeof DesignSystemComponentsBadgeRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/avatar': {
      id: '/design-system/components/avatar'
      path: '/components/avatar'
      fullPath: '/design-system/components/avatar'
      preLoaderRoute: typeof DesignSystemComponentsAvatarRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/alert': {
      id: '/design-system/components/alert'
      path: '/components/alert'
      fullPath: '/design-system/components/alert'
      preLoaderRoute: typeof DesignSystemComponentsAlertRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/ai-icon': {
      id: '/design-system/components/ai-icon'
      path: '/components/ai-icon'
      fullPath: '/design-system/components/ai-icon'
      preLoaderRoute: typeof DesignSystemComponentsAiIconRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/design-system/components/accordion': {
      id: '/design-system/components/accordion'
      path: '/components/accordion'
      fullPath: '/design-system/components/accordion'
      preLoaderRoute: typeof DesignSystemComponentsAccordionRouteImport
      parentRoute: typeof DesignSystemRouteRoute
    }
    '/_app/my-account/{-$slug}': {
      id: '/_app/my-account/{-$slug}'
      path: '/my-account/{-$slug}'
      fullPath: '/my-account/{-$slug}'
      preLoaderRoute: typeof AppMyAccountChar123SlugChar125RouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppFoldersRoute: typeof AppFoldersRoute
  AppFormsRoute: typeof AppFormsRoute
  AppPortalsRoute: typeof AppPortalsRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMyAccountChar123SlugChar125Route: typeof AppMyAccountChar123SlugChar125Route
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppFoldersRoute: AppFoldersRoute,
  AppFormsRoute: AppFormsRoute,
  AppPortalsRoute: AppPortalsRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppTasksRoute: AppTasksRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
  AppMyAccountChar123SlugChar125Route: AppMyAccountChar123SlugChar125Route,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DesignSystemRouteRouteChildren {
  DesignSystemColorsRoute: typeof DesignSystemColorsRoute
  DesignSystemTypographyRoute: typeof DesignSystemTypographyRoute
  DesignSystemIndexRoute: typeof DesignSystemIndexRoute
  DesignSystemComponentsAccordionRoute: typeof DesignSystemComponentsAccordionRoute
  DesignSystemComponentsAiIconRoute: typeof DesignSystemComponentsAiIconRoute
  DesignSystemComponentsAlertRoute: typeof DesignSystemComponentsAlertRoute
  DesignSystemComponentsAvatarRoute: typeof DesignSystemComponentsAvatarRoute
  DesignSystemComponentsBadgeRoute: typeof DesignSystemComponentsBadgeRoute
  DesignSystemComponentsButtonRoute: typeof DesignSystemComponentsButtonRoute
  DesignSystemComponentsDataTableRoute: typeof DesignSystemComponentsDataTableRoute
  DesignSystemComponentsDividerRoute: typeof DesignSystemComponentsDividerRoute
  DesignSystemComponentsDrawerRoute: typeof DesignSystemComponentsDrawerRoute
  DesignSystemComponentsEmptyStateRoute: typeof DesignSystemComponentsEmptyStateRoute
  DesignSystemComponentsFileUploadRoute: typeof DesignSystemComponentsFileUploadRoute
  DesignSystemComponentsFloatingPanelRoute: typeof DesignSystemComponentsFloatingPanelRoute
  DesignSystemComponentsHighlightRoute: typeof DesignSystemComponentsHighlightRoute
  DesignSystemComponentsIconRoute: typeof DesignSystemComponentsIconRoute
  DesignSystemComponentsIconButtonRoute: typeof DesignSystemComponentsIconButtonRoute
  DesignSystemComponentsImageUploadRoute: typeof DesignSystemComponentsImageUploadRoute
  DesignSystemComponentsIndicatorRoute: typeof DesignSystemComponentsIndicatorRoute
  DesignSystemComponentsInputCheckboxRoute: typeof DesignSystemComponentsInputCheckboxRoute
  DesignSystemComponentsInputCheckboxCardRoute: typeof DesignSystemComponentsInputCheckboxCardRoute
  DesignSystemComponentsInputCheckboxGroupRoute: typeof DesignSystemComponentsInputCheckboxGroupRoute
  DesignSystemComponentsInputDateRoute: typeof DesignSystemComponentsInputDateRoute
  DesignSystemComponentsInputNumberRoute: typeof DesignSystemComponentsInputNumberRoute
  DesignSystemComponentsInputPasswordRoute: typeof DesignSystemComponentsInputPasswordRoute
  DesignSystemComponentsInputPinRoute: typeof DesignSystemComponentsInputPinRoute
  DesignSystemComponentsInputRadioRoute: typeof DesignSystemComponentsInputRadioRoute
  DesignSystemComponentsInputRadioCardRoute: typeof DesignSystemComponentsInputRadioCardRoute
  DesignSystemComponentsInputRadioGroupRoute: typeof DesignSystemComponentsInputRadioGroupRoute
  DesignSystemComponentsInputSelectRoute: typeof DesignSystemComponentsInputSelectRoute
  DesignSystemComponentsInputSelectMultipleRoute: typeof DesignSystemComponentsInputSelectMultipleRoute
  DesignSystemComponentsInputSwitchRoute: typeof DesignSystemComponentsInputSwitchRoute
  DesignSystemComponentsInputSwitchGroupRoute: typeof DesignSystemComponentsInputSwitchGroupRoute
  DesignSystemComponentsInputTextRoute: typeof DesignSystemComponentsInputTextRoute
  DesignSystemComponentsInputTextareaRoute: typeof DesignSystemComponentsInputTextareaRoute
  DesignSystemComponentsInputTimeRoute: typeof DesignSystemComponentsInputTimeRoute
  DesignSystemComponentsMenuRoute: typeof DesignSystemComponentsMenuRoute
  DesignSystemComponentsModalRoute: typeof DesignSystemComponentsModalRoute
  DesignSystemComponentsPaginationRoute: typeof DesignSystemComponentsPaginationRoute
  DesignSystemComponentsPopoverRoute: typeof DesignSystemComponentsPopoverRoute
  DesignSystemComponentsProgressRoute: typeof DesignSystemComponentsProgressRoute
  DesignSystemComponentsProgressCircleRoute: typeof DesignSystemComponentsProgressCircleRoute
  DesignSystemComponentsProgressSemiCircleRoute: typeof DesignSystemComponentsProgressSemiCircleRoute
  DesignSystemComponentsQrCodeRoute: typeof DesignSystemComponentsQrCodeRoute
  DesignSystemComponentsRangeSliderRoute: typeof DesignSystemComponentsRangeSliderRoute
  DesignSystemComponentsRatingRoute: typeof DesignSystemComponentsRatingRoute
  DesignSystemComponentsScrollAreaRoute: typeof DesignSystemComponentsScrollAreaRoute
  DesignSystemComponentsSegmentGroupRoute: typeof DesignSystemComponentsSegmentGroupRoute
  DesignSystemComponentsSignaturePadRoute: typeof DesignSystemComponentsSignaturePadRoute
  DesignSystemComponentsSliderRoute: typeof DesignSystemComponentsSliderRoute
  DesignSystemComponentsStepperRoute: typeof DesignSystemComponentsStepperRoute
  DesignSystemComponentsTableRoute: typeof DesignSystemComponentsTableRoute
  DesignSystemComponentsTabsRoute: typeof DesignSystemComponentsTabsRoute
  DesignSystemComponentsTimelineRoute: typeof DesignSystemComponentsTimelineRoute
  DesignSystemComponentsToastRoute: typeof DesignSystemComponentsToastRoute
  DesignSystemComponentsTooltipRoute: typeof DesignSystemComponentsTooltipRoute
  DesignSystemComponentsTourRoute: typeof DesignSystemComponentsTourRoute
  DesignSystemComponentsTreeRoute: typeof DesignSystemComponentsTreeRoute
  DesignSystemComponentsIndexRoute: typeof DesignSystemComponentsIndexRoute
}

const DesignSystemRouteRouteChildren: DesignSystemRouteRouteChildren = {
  DesignSystemColorsRoute: DesignSystemColorsRoute,
  DesignSystemTypographyRoute: DesignSystemTypographyRoute,
  DesignSystemIndexRoute: DesignSystemIndexRoute,
  DesignSystemComponentsAccordionRoute: DesignSystemComponentsAccordionRoute,
  DesignSystemComponentsAiIconRoute: DesignSystemComponentsAiIconRoute,
  DesignSystemComponentsAlertRoute: DesignSystemComponentsAlertRoute,
  DesignSystemComponentsAvatarRoute: DesignSystemComponentsAvatarRoute,
  DesignSystemComponentsBadgeRoute: DesignSystemComponentsBadgeRoute,
  DesignSystemComponentsButtonRoute: DesignSystemComponentsButtonRoute,
  DesignSystemComponentsDataTableRoute: DesignSystemComponentsDataTableRoute,
  DesignSystemComponentsDividerRoute: DesignSystemComponentsDividerRoute,
  DesignSystemComponentsDrawerRoute: DesignSystemComponentsDrawerRoute,
  DesignSystemComponentsEmptyStateRoute: DesignSystemComponentsEmptyStateRoute,
  DesignSystemComponentsFileUploadRoute: DesignSystemComponentsFileUploadRoute,
  DesignSystemComponentsFloatingPanelRoute:
    DesignSystemComponentsFloatingPanelRoute,
  DesignSystemComponentsHighlightRoute: DesignSystemComponentsHighlightRoute,
  DesignSystemComponentsIconRoute: DesignSystemComponentsIconRoute,
  DesignSystemComponentsIconButtonRoute: DesignSystemComponentsIconButtonRoute,
  DesignSystemComponentsImageUploadRoute:
    DesignSystemComponentsImageUploadRoute,
  DesignSystemComponentsIndicatorRoute: DesignSystemComponentsIndicatorRoute,
  DesignSystemComponentsInputCheckboxRoute:
    DesignSystemComponentsInputCheckboxRoute,
  DesignSystemComponentsInputCheckboxCardRoute:
    DesignSystemComponentsInputCheckboxCardRoute,
  DesignSystemComponentsInputCheckboxGroupRoute:
    DesignSystemComponentsInputCheckboxGroupRoute,
  DesignSystemComponentsInputDateRoute: DesignSystemComponentsInputDateRoute,
  DesignSystemComponentsInputNumberRoute:
    DesignSystemComponentsInputNumberRoute,
  DesignSystemComponentsInputPasswordRoute:
    DesignSystemComponentsInputPasswordRoute,
  DesignSystemComponentsInputPinRoute: DesignSystemComponentsInputPinRoute,
  DesignSystemComponentsInputRadioRoute: DesignSystemComponentsInputRadioRoute,
  DesignSystemComponentsInputRadioCardRoute:
    DesignSystemComponentsInputRadioCardRoute,
  DesignSystemComponentsInputRadioGroupRoute:
    DesignSystemComponentsInputRadioGroupRoute,
  DesignSystemComponentsInputSelectRoute:
    DesignSystemComponentsInputSelectRoute,
  DesignSystemComponentsInputSelectMultipleRoute:
    DesignSystemComponentsInputSelectMultipleRoute,
  DesignSystemComponentsInputSwitchRoute:
    DesignSystemComponentsInputSwitchRoute,
  DesignSystemComponentsInputSwitchGroupRoute:
    DesignSystemComponentsInputSwitchGroupRoute,
  DesignSystemComponentsInputTextRoute: DesignSystemComponentsInputTextRoute,
  DesignSystemComponentsInputTextareaRoute:
    DesignSystemComponentsInputTextareaRoute,
  DesignSystemComponentsInputTimeRoute: DesignSystemComponentsInputTimeRoute,
  DesignSystemComponentsMenuRoute: DesignSystemComponentsMenuRoute,
  DesignSystemComponentsModalRoute: DesignSystemComponentsModalRoute,
  DesignSystemComponentsPaginationRoute: DesignSystemComponentsPaginationRoute,
  DesignSystemComponentsPopoverRoute: DesignSystemComponentsPopoverRoute,
  DesignSystemComponentsProgressRoute: DesignSystemComponentsProgressRoute,
  DesignSystemComponentsProgressCircleRoute:
    DesignSystemComponentsProgressCircleRoute,
  DesignSystemComponentsProgressSemiCircleRoute:
    DesignSystemComponentsProgressSemiCircleRoute,
  DesignSystemComponentsQrCodeRoute: DesignSystemComponentsQrCodeRoute,
  DesignSystemComponentsRangeSliderRoute:
    DesignSystemComponentsRangeSliderRoute,
  DesignSystemComponentsRatingRoute: DesignSystemComponentsRatingRoute,
  DesignSystemComponentsScrollAreaRoute: DesignSystemComponentsScrollAreaRoute,
  DesignSystemComponentsSegmentGroupRoute:
    DesignSystemComponentsSegmentGroupRoute,
  DesignSystemComponentsSignaturePadRoute:
    DesignSystemComponentsSignaturePadRoute,
  DesignSystemComponentsSliderRoute: DesignSystemComponentsSliderRoute,
  DesignSystemComponentsStepperRoute: DesignSystemComponentsStepperRoute,
  DesignSystemComponentsTableRoute: DesignSystemComponentsTableRoute,
  DesignSystemComponentsTabsRoute: DesignSystemComponentsTabsRoute,
  DesignSystemComponentsTimelineRoute: DesignSystemComponentsTimelineRoute,
  DesignSystemComponentsToastRoute: DesignSystemComponentsToastRoute,
  DesignSystemComponentsTooltipRoute: DesignSystemComponentsTooltipRoute,
  DesignSystemComponentsTourRoute: DesignSystemComponentsTourRoute,
  DesignSystemComponentsTreeRoute: DesignSystemComponentsTreeRoute,
  DesignSystemComponentsIndexRoute: DesignSystemComponentsIndexRoute,
}

const DesignSystemRouteRouteWithChildren =
  DesignSystemRouteRoute._addFileChildren(DesignSystemRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  DesignSystemRouteRoute: DesignSystemRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
